### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by jangxyz** [dailyjs-white-ox/wysi-mark-svelte#7]
기본 기능

- [x] 텍스트로 **markdown을 편집**할 수 있다.
- [x] markdown은 **HTML로 렌더링**된다.
- [x] `---` 는 다음 slide로 넘어가는 등 **slide 특화된 문법**이 몇개 있다.
- [x] 렌더링된 HTML을 포인터로 선택해서 **크기나 위치, 스타일** 등을 줄 수 있다.
- [ ] **저장 및 불러오기** 등을 할 수 있다.
- [ ] **svelte component**를 사용할 수 있다.

추가 기능

- 코드를 잘 보여줄 수 있다.
    - [ ] syntax highlighting
    - [ ] 긴 코드도 무리없이 (folding, scrolling)
    - [ ] 특정 부분만 (줄, 단어) highlight

- [ ] transition을 쉽게 넣을 수 있다.

- 코드 고급 편집:
    - [ ] 코드를 수정하고, 적용해서 결과를 확인할 수 있다.
        - svelte
        - typescript
        - python
        - stackblitz
        - …
    - [ ] 코드의 버전을 관리할 수 있다.
    
- 소스에서 손쉽게 스타일을 줄 수 있다.
    - [ ] frontmatter
    - [ ] apply user-defined styles (`+layout`?)
    - [ ] apply ~~pug~~ 🐶
        - (example)
            
            ```markdown
            .flex
              .left
                Contents:
                * One
                * Two
                * Three
            
              .right
            		### Contents here..
            ```
            
    
- 외부에서 component를 불러올 수 있다.
    - [ ] svelte-repl 에 있는 코드 바로 가져오기
    - [ ] npm에서 가져오기
    - [ ] raw file에서 가져오기
    - [ ] github에서 가져오기

- [ ] 로그인, clone, follow, like 등을 할 수 있다.
